openapi: "3.0.3"
info:
  description: |
    OAuth Authentication
    --------------------
      
    You can register your own OAuth app using the `/api/v1/oauth/apps/` endpoint. Proceed to the standard OAuth flow afterwards:
      

  version: "0.0.1"
  title: "Sample API"

servers:
  - url: http://{domain}
    description: Custom server
    variables:
      domain:
        default: localhost:3000
        description: Your Funkwhale Domain
      protocol:
        enum:
          - 'http'
        default: 'http'

components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2 with the Authorization Code flow.
      flows:
        authorizationCode:
          authorizationUrl: /as/authorization.oauth2
          tokenUrl: http://localhost:3000/token
          scopes: {}
    # jwt:
    #   type: http
    #   scheme: bearer
    #   bearerFormat: JWT
    #   description: "You can get a token by using the /token endpoint"

security:
  - jwt: []
  - oauth2: []

tags:
  - name: Auth and security
    description: authorization endpoints


paths:
  /token:
    get:
      tags:
        - "Auth and security"
      summary:
        Request an OAuth bearer token in exchange of an authorization_code.
      security: []
      responses:
        200:
  /secure-endpoint:
    post:
      tags:
        - "Auth and security"
      summary:
        Super secure end-point
      security: 
        - oauth2: []
      responses:
        201:
          content:
            application/json:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: "string"
                  example: "some random string"
                  summary: "A human readable name for your app"
                redirect_uris:
                  type: "string"
                  example: "where to redirect?"
                  summary: "A list of redirect uris, separated by spaces"
  
responses:
  200:
    description: Success
  201:
    description: Successfully created
  204:
    description: Successfully deleted
  400:
    description: Bad request